grails-app/domain/demo/Blog.groovy
package demo

class Blog {
    String name
    String content

    SortedSet<BlogEntry> blogEntries

    static hasMany = [blogEntries: BlogEntry]
    static constraints = {
    }
}

grails-app/domain/demo/BlogEntry.groovy
package demo

class BlogEntry implements Comparable<BlogEntry> {
    String title
    String content
    BlogEntryStatus blogEntryStatus = BlogEntryStatus.DRAFT
    Date publishDate
    Date published
    Date dateCreated // Automatic maintained by Grails

    static belongsTo = [blog: Blog]

    static constraints = {
        publishDate nullable: true, validator: { value, object ->
            if (object.blogEntryStatus == BlogEntryStatus.READY_TO_PUBLISH) {
                if (!value) {
                    return ['must.be.set']
                }
                if(value.before(new Date())) {
                    return ['must.be.in.future']
                }
            }
        }
        publishDate nullable: true
        published nullable: true

    }

    def beforeInsert() {
        updatePublishedDate()
    }

    def beforeUpdate() {
        updatePublishedDate()
    }

    private void updatePublishedDate() {
        if (!published && blogEntryStatus == BlogEntryStatus.PUBLISHED) {
            published = new Date()
        }
    }

    @Override
    int compareTo(BlogEntry other) {
        return publishDate <=> other.publishDate ?: dateCreated <=> other.dateCreated
    }
}

grails-app/domain/demo/Tag.groovy
package demo

class Tag {
    String label
    static constraints = {
    }
}

grails-app/controllers/demo/BlogController.groovy
package demo



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class BlogController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Blog.list(params), model:[blogInstanceCount: Blog.count()]
    }

    def show(Blog blogInstance) {
        respond blogInstance
    }

    def create() {
        respond new Blog(params)
    }

    @Transactional
    def save(Blog blogInstance) {
        if (blogInstance == null) {
            notFound()
            return
        }

        if (blogInstance.hasErrors()) {
            respond blogInstance.errors, view:'create'
            return
        }

        blogInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'blog.label', default: 'Blog'), blogInstance.id])
                redirect blogInstance
            }
            '*' { respond blogInstance, [status: CREATED] }
        }
    }

    def edit(Blog blogInstance) {
        respond blogInstance
    }

    @Transactional
    def update(Blog blogInstance) {
        if (blogInstance == null) {
            notFound()
            return
        }

        if (blogInstance.hasErrors()) {
            respond blogInstance.errors, view:'edit'
            return
        }

        blogInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Blog.label', default: 'Blog'), blogInstance.id])
                redirect blogInstance
            }
            '*'{ respond blogInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Blog blogInstance) {

        if (blogInstance == null) {
            notFound()
            return
        }

        blogInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Blog.label', default: 'Blog'), blogInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'blog.label', default: 'Blog'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/controllers/demo/BlogEntryController.groovy
package demo


import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class BlogEntryController {
    def blogEntryService
    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond blogEntryService.list(params), model: [blogEntryInstanceCount: blogEntryService.count()]
    }

    def show(BlogEntry blogEntryInstance) {
        respond blogEntryInstance
    }

    def create() {
        respond new BlogEntry(params)
    }

    @Transactional
    def save(BlogEntry blogEntryInstance) {
        if (blogEntryInstance == null) {
            notFound()
            return
        }

        if (blogEntryInstance.hasErrors()) {
            respond blogEntryInstance.errors, view: 'create'
            return
        }

        blogEntryService.save blogEntryInstance

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'blogEntry.label', default: 'BlogEntry'), blogEntryInstance.id])
                redirect blogEntryInstance
            }
            '*' { respond blogEntryInstance, [status: CREATED] }
        }
    }

    def edit(BlogEntry blogEntryInstance) {
        respond blogEntryInstance
    }

    @Transactional
    def update(BlogEntry blogEntryInstance) {
        if (blogEntryInstance == null) {
            notFound()
            return
        }

        if (blogEntryInstance.hasErrors()) {
            respond blogEntryInstance.errors, view: 'edit'
            return
        }

        blogEntryService.save blogEntryInstance

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'BlogEntry.label', default: 'BlogEntry'), blogEntryInstance.id])
                redirect blogEntryInstance
            }
            '*' { respond blogEntryInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(BlogEntry blogEntryInstance) {

        if (blogEntryInstance == null) {
            notFound()
            return
        }

        blogEntryService.delete blogEntryInstance

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'BlogEntry.label', default: 'BlogEntry'), blogEntryInstance.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'blogEntry.label', default: 'BlogEntry'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/controllers/demo/DataRestController.groovy
package demo

import grails.converters.JSON
import grails.converters.XML

import javax.servlet.http.HttpServletResponse

/**
 * See UrlMappings
 */
class DataRestController {
    def dataService

    static allowedMethods = [counties: 'GET', countiesExtended: 'GET']

    static defaultAction = 'counties'

    def counties(boolean enhanced) {
        List<County> counties = enhanced ? dataService.countiesWithMunicipals : dataService.counties
        withFormat {
            html {
                response.sendError(HttpServletResponse.SC_NOT_IMPLEMENTED, "HTML Not supported")
            }
            json {
                render counties as JSON
            }
            xml {
                render counties as XML
            }
        }
    }
}

grails-app/controllers/demo/TagController.groovy
package demo
import grails.rest.RestfulController
import grails.transaction.Transactional

@Transactional(readOnly = true)
class TagController extends RestfulController<Tag> {
    TagController() {
        super(Tag)
    }


    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)

        def resources = listAllResources(params)

        respond resources
    }
}

grails-app/views/blog/_form.gsp
<%@ page import="demo.Blog" %>



<div class="fieldcontain ${hasErrors(bean: blogInstance, field: 'blogEntries', 'error')} ">
	<label for="blogEntries">
		<g:message code="blog.blogEntries.label" default="Blog Entries" />
		
	</label>
	
<ul class="one-to-many">
<g:each in="${blogInstance?.blogEntries?}" var="b">
    <li><g:link controller="blogEntry" action="show" id="${b.id}">${b?.encodeAsHTML()}</g:link></li>
</g:each>
<li class="add">
<g:link controller="blogEntry" action="create" params="['blog.id': blogInstance?.id]">${message(code: 'default.add.label', args: [message(code: 'blogEntry.label', default: 'BlogEntry')])}</g:link>
</li>
</ul>


</div>

<div class="fieldcontain ${hasErrors(bean: blogInstance, field: 'content', 'error')} required">
	<label for="content">
		<g:message code="blog.content.label" default="Content" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="content" required="" value="${blogInstance?.content}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: blogInstance, field: 'name', 'error')} required">
	<label for="name">
		<g:message code="blog.name.label" default="Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="name" required="" value="${blogInstance?.name}"/>

</div>

grails-app/views/blog/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'blog.label', default: 'Blog')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-blog" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-blog" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${blogInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${blogInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:blogInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/blog/edit.gsp
<%@ page import="demo.Blog" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'blog.label', default: 'Blog')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-blog" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-blog" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${blogInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${blogInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:blogInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${blogInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/blog/index.gsp
<%@ page import="demo.Blog" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'blog.label', default: 'Blog')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-blog" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-blog" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="content" title="${message(code: 'blog.content.label', default: 'Content')}" />
					
						<g:sortableColumn property="name" title="${message(code: 'blog.name.label', default: 'Name')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${blogInstanceList}" status="i" var="blogInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${blogInstance.id}">${fieldValue(bean: blogInstance, field: "content")}</g:link></td>
					
						<td>${fieldValue(bean: blogInstance, field: "name")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${blogInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/blog/show.gsp
<%@ page import="demo.Blog" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'blog.label', default: 'Blog')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-blog" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-blog" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list blog">
			
				<g:if test="${blogInstance?.blogEntries}">
				<li class="fieldcontain">
					<span id="blogEntries-label" class="property-label"><g:message code="blog.blogEntries.label" default="Blog Entries" /></span>
					
						<g:each in="${blogInstance.blogEntries}" var="b">
						<span class="property-value" aria-labelledby="blogEntries-label"><g:link controller="blogEntry" action="show" id="${b.id}">${b?.encodeAsHTML()}</g:link></span>
						</g:each>
					
				</li>
				</g:if>
			
				<g:if test="${blogInstance?.content}">
				<li class="fieldcontain">
					<span id="content-label" class="property-label"><g:message code="blog.content.label" default="Content" /></span>
					
						<span class="property-value" aria-labelledby="content-label"><g:fieldValue bean="${blogInstance}" field="content"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${blogInstance?.name}">
				<li class="fieldcontain">
					<span id="name-label" class="property-label"><g:message code="blog.name.label" default="Name" /></span>
					
						<span class="property-value" aria-labelledby="name-label"><g:fieldValue bean="${blogInstance}" field="name"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:blogInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${blogInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/layouts/main.gsp
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"><!--<![endif]-->
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title><g:layoutTitle default="Grails"/></title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="shortcut icon" href="${assetPath(src: 'favicon.ico')}" type="image/x-icon">
		<link rel="apple-touch-icon" href="${assetPath(src: 'apple-touch-icon.png')}">
		<link rel="apple-touch-icon" sizes="114x114" href="${assetPath(src: 'apple-touch-icon-retina.png')}">
  		<asset:stylesheet src="application.css"/>
		<asset:javascript src="application.js"/>
		<g:layoutHead/>
	</head>
	<body>
		<div id="grailsLogo" role="banner"><a href="http://grails.org"><asset:image src="grails_logo.png" alt="Grails"/></a></div>
		<g:layoutBody/>
		<div class="footer" role="contentinfo"></div>
		<div id="spinner" class="spinner" style="display:none;"><g:message code="spinner.alt" default="Loading&hellip;"/></div>
	</body>
</html>